site_name: IaC Guide For ACP (Terraform Edition)
theme:
  name: material

nav:
  - Introduction: ./index.md
  - Terraform Integration with ACP: ./acp_terraform_integration.md
  - ACP Resource Management: ./acp_resource_management.md
  - FAQ: ./FQA.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

docs_dir: ./guide

use_directory_urls: false

plugins:
  - search
  - with-pdf:
      author: "Alauda Team"
      copyright: "Alauda Team"
      cover_logo: ./assets/logo.svg
      cover_title: IaC Guide For ACP
      cover_subtitle: Terraform Edition
      output_path: acp_terraform_guide.pdf